name: LunaLog
options:
  bundleIdPrefix: com.seros
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: tr
  xcodeVersion: "1500"

packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk.git
    minorVersion: "11.0.0"
  google-sign-in-ios:
    url: https://github.com/google/GoogleSignIn-iOS.git
    minorVersion: "8.0.0"

settings:
  base:
    SWIFT_VERSION: "5.0"

targets:
  LunaLog:
    type: application
    platform: iOS
    sources:
      - path: LunaLog
        excludes:
          - "Views/Backup/**"
          - "Info.plist"
    info:
      path: LunaLog/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - com.googleusercontent.apps.186549224959-0jsodb75opmjce7vtv7tp1qqs7jiu8jj
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleDisplayName: LunaLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.seros.LunaLog
        CODE_SIGN_ENTITLEMENTS: LunaLog/LunaLog.entitlements
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: LunaLog/Info.plist
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies:
      - target: LunaLogWidgetExtension
      - package: firebase-ios-sdk
        product: FirebaseAuth
      - package: firebase-ios-sdk
        product: FirebaseFirestore
      - package: firebase-ios-sdk
        product: FirebaseFirestoreSwift
      - package: google-sign-in-ios
        product: GoogleSignIn
      - package: google-sign-in-ios
        product: GoogleSignInSwift

  LunaLogWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: LunaLogWidget
        excludes:
          - Info.plist
      - path: LunaLog/Models/Period.swift
      - path: LunaLog/Models/Strings.swift
    info:
      path: LunaLogWidget/Info.plist
      properties:
        CFBundleDisplayName: "LunaLog Widget"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.seros.LunaLog.Widget
        CODE_SIGN_ENTITLEMENTS: LunaLogWidget/LunaLogWidget.entitlements
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: LunaLogWidget/Info.plist
        SKIP_INSTALL: YES
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@executable_path/../../Frameworks"
    frameworks:
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
