name: LunaLog
options:
  bundleIdPrefix: com.seros
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: tr
  xcodeVersion: "1500"

settings:
  base:
    SWIFT_VERSION: "5.0"

targets:
  LunaLog:
    type: application
    platform: iOS
    sources:
      - path: LunaLog
        excludes:
          - "Views/Backup/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.seros.LunaLog
        INFOPLIST_KEY_CFBundleDisplayName: "LunaLog"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CODE_SIGN_ENTITLEMENTS: LunaLog/LunaLog.entitlements
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies:
      - target: LunaLogWidgetExtension

  LunaLogWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: LunaLogWidget
        excludes:
          - Info.plist
      - path: LunaLog/Models/Period.swift
      - path: LunaLog/Models/Strings.swift
    info:
      path: LunaLogWidget/Info.plist
      properties:
        CFBundleDisplayName: "LunaLog Widget"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.seros.LunaLog.Widget
        CODE_SIGN_ENTITLEMENTS: LunaLogWidget/LunaLogWidget.entitlements
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: LunaLogWidget/Info.plist
        SKIP_INSTALL: YES
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@executable_path/../../Frameworks"
    frameworks:
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
